### ISSUE TITLE
[Frontend] Add social bar

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/seismic-risc-client#1]
The social bar should contain
- [Facebook](https://en.facebookbrand.com/#brand-guidelines-assets) icon to [code4ro](https://www.facebook.com/code4romania)
- [Instagram](https://en.instagram-brand.com/assets/icons) icon to [code4ro](https://www.instagram.com/code4romania/)
- [LinkedIn](https://brand.linkedin.com/downloads) icon to [code4ro](https://www.linkedin.com/company/code4romania/)
- [Twitter](https://about.twitter.com/en_us/company/brand-resources.html) icon to [code4ro](https://twitter.com/Code4Romania)
- "donation" button to [code4ro](https://code4.ro/doneaza/)

While in the specification a search bar also appears, this shouldn't be implemented yet.

[Pages 1-3 from the specs](https://www.figma.com/file/qOyFrU8T6LXnJw7YcoVW85/Seismic-Risk)

**Comment by DanielStoica85** [comment]
Mind if I work on this one?

**Comment by tudoramariei** [comment]
Hey, @DanielStoica85! Don't mind if you do
Since I see you're from Bucharest, I'd invite you to tomorrow's [HackDay](https://tfsg.code4.ro/ro/hackday/); this way you can also join the Slack group to keep on with all the discussions

**Comment by DanielStoica85** [comment]
Hey, @tudoramariei 

Actually, my location is not up-to-date. I am leaving in Eindhoven, Netherlands. So I won't be able to join the hack day. But I would be happy to contribute to this project (and other React projects) from home. :)

**Comment by tudoramariei** [comment]
Alright, then. If you want to work on it, it's all yours!
If you also want to be in the community, you can [register](https://tfsg.code4.ro/ro/hackday/) remote
Either way, thanks a lot for contributing! 🙇

**Comment by DanielStoica85** [comment]
Thanks! I'm on it.
P.S. I am open to taking other tasks as well.

**Comment by tudoramariei** [comment]
Issue closed, thanks @DanielStoica85
