### ISSUE TITLE
[Frontend] Create homepage

### ISSUE THREAD

**Issue by catileptic** [code4romania/seismic-risc-client#8]
As a user I want to be able to see the following elements, on the homepage:

* a way to add a new building
* a map of the buildings that present a risk, already pinned on the map
* the ability to filter the buildings (pins) by risk category 
* a search bar
* statistics on the total number of people at risk, the number of evaluated buildings and the number of consolidated buildings

For visual reference, use [the first page of the Figma mockup](https://www.figma.com/file/qOyFrU8T6LXnJw7YcoVW85/Seismic-Risk?node-id=0%3A1).

**Comment by dmfarcas** [comment]
Hello. 

I can work on this task. Could you assign it to me?

Thanks.

**Comment by RaduCStefanescu** [comment]
In progress @dmfarcas

**Comment by horatiubota** [comment]
Any progress with this? I'd like to take it for hackday#12.

**Comment by horatiubota** [comment]
Taking this for hackday#12.

**Comment by tudoramariei** [comment]
I think you can take it @horatiubota 
You can also look at #19 since it was quite good, it only needed to use Here maps instead of Google

**Comment by tudoramariei** [comment]
Issue closed, thanks @horatiubota
